export const QUESTIONS_GET_REQUEST = 'QUESTIONS_GET_REQUEST';
export const QUESTIONS_GET_SUCCESS = 'QUESTIONS_GET_SUCCESS';
export const QUESTIONS_GET_FAILURE = 'QUESTIONS_GET_FAILURE';

export const QUESTIONS_CREATE_REQUEST = 'QUESTIONS_CREATE_REQUEST';
export const QUESTIONS_CREATE_SUCCESS = 'QUESTIONS_CREATE_SUCCESS';
export const QUESTIONS_CREATE_FAILURE = 'QUESTIONS_CREATE_FAILURE';
